<a href="https://colab.research.google.com/github/jdansb/Econophysics/blob/main/files/contsocial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
A = np.array([[45/5, 0.08,0.01],
              [0.18, 0.21, 0.11],
              [0.00, 0.05, 0.00]])
I = np.eye(3)
M=I-A
L = np.linalg.inv(M)
print(L)

[[1.1216677  0.11509783 0.02387744]
 [0.25736161 1.30110594 0.14569527]
 [0.01286808 0.0650553  1.00728476]]


In [7]:
v = np.array([[200],[2000],[1808]])
x=np.dot(L, v)
print(x)

[[ 497.6996161 ]
 [2917.10125035]
 [1953.85506252]]


In [12]:
240/2900

0.08275862068965517