<a href="https://colab.research.google.com/github/jdansb/Econophysics/blob/main/files/contsocial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [13]:
A = np.array([[45/500, 240/2900,15/1952],
              [0.18, 0.21, 0.11],
              [0.00, 0.05, 0.00]])
I = np.eye(3)
M=I-A
L = np.linalg.inv(M)
print(L)

[[1.12243114 0.11895744 0.02171056]
 [0.25753678 1.30199151 0.14519809]
 [0.01287684 0.06509958 1.0072599 ]]


In [7]:
v = np.array([[200],[2000],[1808]])
x=np.dot(L, v)
print(x)

[[ 497.6996161 ]
 [2917.10125035]
 [1953.85506252]]


In [12]:
240/2900

0.08275862068965517

In [14]:
A

array([[0.09      , 0.08275862, 0.00768443],
       [0.18      , 0.21      , 0.11      ],
       [0.        , 0.05      , 0.        ]])