<a href="https://colab.research.google.com/github/jdansb/Econophysics/blob/main/files/contsocial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
A = np.array([[45/500, 240/2900,15/1952],
              [90/500, 600/2900,210/1952],
              [0.00, 144/2900, 0.00]])
print('A matriz de coeficientes A é:')
print(A)
I = np.eye(3)
M=I-A
L = np.linalg.inv(M)
print('A matriz de Leontieff é:')
print(L)

A matriz de coeficientes A é:
[[0.09       0.08275862 0.00768443]
 [0.18       0.20689655 0.10758197]
 [0.         0.04965517 0.        ]]
A matriz L é:
[[1.12233089 0.11845059 0.02136762]
 [0.25644763 1.29648526 0.14144909]
 [0.01273395 0.0643772  1.00702368]]


In [7]:
v = np.array([[200],[2000],[1808]])
print('Se a demanda é:')
print(v)
x=np.dot(L, v)
print('Então a produção bruta necessária é:')
print(x)

Se a demanda é:
[[ 200]
 [2000]
 [1808]]
Então a produção bruta necessária é:
[[ 500.]
 [2900.]
 [1952.]]


In [45]:
print('A produção Bruta total é:',sum(x)[0])
print('A demanda total é:',sum(v)[0])
X = np.array([[A[0][0]*x[0][0],A[0][1]*x[1][0],A[0][2]*x[2][0]],
              [A[1][0]*x[0][0],A[1][1]*x[1][0],A[1][2]*x[2][0]],
              [A[2][0]*x[0][0],A[2][1]*x[1][0],A[2][2]*x[2][0]]])
print('E a matriz de insumos-produtos é:')
print(X)

A produção Bruta total é: 5352.0
A demanda total é: 4008
E a matriz de insumos-produtos é:
[[ 45. 240.  15.]
 [ 90. 600. 210.]
 [  0. 144.   0.]]
