<a href="https://colab.research.google.com/github/jdansb/Econophysics/blob/main/files/contsocial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  ## Basic Concepts


The double-entry bookkeeping principle states that for every debit entry there must always correspond another credit entry of the same value. Internal balance refers to the requirement of equality between debit and credit values in each account, while external balance implies the need for balance across all accounts in the system.

Once accounting is chosen as the instrument for the macroscopic measurement of economic movement, it follows that the economy of an entire country can be seen as that of a single large firm: the results of its operation over a given period are presented by the accounts that make up the system of national accounts.

What is conventionally called “social accounting” is not limited to the system of national accounts, but also includes other key components such as the balance of payments, the monetary system accounts, and social indicators such as income distribution and the human development index. For this reason, the analogy should be restricted solely to its form — accounts, balance sheets, and bookkeeping entries. Its substance and objectives are entirely different.

Since the accounting we are referring to is social in nature, all the statistical “effort” must serve to give civil society a clearer idea of the direction of a country, and thus allow it to intervene in these directions when necessary.

In the economic system in which we live, everything can be evaluated monetarily. Thus, the immense range of different goods and services that an economy is capable of producing can be transformed into a thing of the same substance, namely money. This is what makes it possible to measure aggregates such as national product and national income.

One of the fundamental notions of social accounting is that of identity. But here identity has a particular meaning: it is an accounting identity, and therefore the symbol $\equiv$ is usually used instead of the equality sign $=$. If we take exchange as an example, it implies two operations that are the inverse of one another — the buyer exchanges \$10 for a shirt and the seller exchanges a shirt for \$10 — but which, from an analytical point of view, form an identity, since one cannot exist without the other. Examples: just as a purchase cannot occur without a sale, neither can production exist without simultaneously constituting an expenditure and a generation of income. It is from the identity
$$
\text{product} \equiv \text{expenditure} \equiv \text{income}
$$
that the circular flow of income is derived. Similarly, saving necessarily implies investment, and investment cannot be understood without also considering it, in turn, as saving.

To arrive at the aggregate product of the economy, it is necessary to deduct from the gross value of production the value of intermediate consumption, that is, what was used as input in production. Here, by final good we mean a good that is sold to final consumers, that is, a good that will not be used as an input. By definition, every final good must have its value included in the calculation of output, but not every good whose value enters the calculation of output is a final good by nature. This is because those products that have not yet been consumed, and are not considered final products (that is, were produced to be used as inputs), are also included in the final product. In other words, the aggregate product of the economy is the combination of products sold to final consumers and products not consumed in the period. A final consumer is the economic agent who acquires a good or service that will not be used for resale or as an input in a new production process.

This approach is known as the expenditure approach and evaluates the product of an economy by considering the sum of the values of all goods and services produced in the period that were not destroyed or absorbed as inputs in the production of other goods and services. However, there are still two other ways to approach the issue. From the product (output) perspective, the evaluation of the total product of the economy consists of considering the value actually added by the production process in each productive unit. That is, if we look firm by firm, the value added is given by the difference between the value of its production and the value of the production it acquired as inputs. This is effectively the contribution of each firm to the formation of the total product of the economy.

Both results must be identical. But there is still another way to approach the issue, namely through the income perspective. We must begin by understanding what is called the production process: let us initially assume that there are only two factors of production: labor and another which we will generically call capital — concretely, this includes not only machines and other equipment, but the entire set of elements that constitute the objective conditions without which the production process cannot take place. It is therefore between capital and labor that the product generated by the economy must be distributed, since their participation in the production process is what ensured the creation of this product. It is also possible to include land as a third factor, but this does not substantially change the discussion. The remuneration of the labor factor is called wages, and the remuneration of the capital factor is called profit. Land, in turn, would correspond to rent.

Thus, over a given period of time, the remuneration of both factors, taken jointly, must equal in value the product obtained by the economy in that same period, since these remunerations are nothing more than the distribution of the product. The remunerations paid constitute what we call income. It is not difficult to see that, in this way, the identity
$$
\text{product} \equiv \text{income}
$$
is established. Therefore, the product generated by an economy in a given period of time is equal to the income generated in that same period.

Some additional remarks are that here, unlike in Marxism, money and currency are presented as synonyms, as are value and price. Moreover, society is divided into two groups in a different way. It reads: “The members that constitute society appear twice in the process of its material reproduction and play two distinct roles: at one moment, they are producers; at another, they appear as consumers of what has been produced.” In other words, both the worker and the capitalist are simultaneously producers and consumers. This also becomes evident when we see the factors of production—“labor” and “capital”—side by side, each being responsible for producing “value” equally. That is, in the production process, the worker contributes labor, and the capitalist contributes capital, both in parity. This also appears in the next emphasis given by the book: in addition to playing the role of consumers, households also hold the condition of owners of the factors of production, and it is in this capacity that they secure their access to the goods and services produced. Here, by “ownership of the factors of production,” we understand that workers only possess labor power to sell.

We thus have that the output approach considers the activity of individuals as producers, that is, the activity of productive units or firms. Finally, the income approach analyzes individuals in their condition as owners of factors of production. Transactions occur between households and firms and involve reciprocally determined flows of concrete goods and services, on the one hand, and money, on the other. Following the book, we have this flow:

1. Households supply firms with the factors of production they own and, in return, receive from firms an income, that is, a monetary remuneration;

2. Firms combine these factors in a process called the production process and obtain, as a result, a set of goods and services;

3. With the income received in exchange for the use, in production, of the factors they own, households purchase from firms the goods and services produced by them;

4. Households consume the goods and services;

Observe how this flow places “households” of workers and households of capitalists on equal footing. Income (wages or profits) is seen as a “reward” for their contribution to the production process. Concluding the chapter, we must clearly understand that the flow is that of income and not of product: the money that remunerates the factors of production is the same that returns to firms in the purchase of final goods and services. This does not occur with other goods.

## Basic Structure of National Accounts

The greatest simplifications are typically to consider a closed economy without government; we will work with this example.

Indeed, everything that is produced in a given period but is not consumed in that same period—meaning that it gives rise to consumption in the future—has a name: it is called investment. Investment is divided into fixed capital formation and changes in inventories. Investment is usually split into changes in inventories, which group goods whose future consumption occurs all at once, and gross fixed capital formation, which comprises goods that do not disappear after a single use and enable production over a given period of time.

The depreciation of fixed capital is called depreciation: fixed capital goods also wear out over time and through use, so that, at the end of a given period, their value will have been entirely absorbed by the flow of production of goods that occurred during that period. To obtain the net product of an economy in a given period, it is necessary to deduct from the gross product the portion destined for the replacement of the economy’s capital stock, that is, depreciation.

|       | **Debit**          |       | **Credit**               |
|-------|-------------------|-------|--------------------------|
| **A** | Net Product       | **C** | Personal Consumption     |
| **B** | Depreciation      | **D** | Change in Inventories    |
|       |                   | **E** | Gross Fixed Capital Formation |
|       | **Gross Product** |       | **Gross Expenditure**    |

With respect to remuneration, in addition to wages and profits, we must introduce two other categories of remuneration: rents (which remunerate owners of real estate in general) and interest (which remunerates owners of monetary capital). The only additional caution that must be taken is to avoid double counting, which may occur if we include in these items not only rents and interest paid to households, but also those paid to firms. The latter must not be considered because, as revenues, they are already included in the profit and loss statements of firms. The exception is the financial sector, but this (maybe) will be discussed later.

| **Debit**          |                                   |   | **Credit**                     |
|--------------------|-----------------------------------|---|--------------------------------|
| $\boldsymbol{a}_{1}$ | wages                             | C | Personal Consumption           |
| $\boldsymbol{a}_{2}$ | profits                          | D | Change in inventories         |
| $\boldsymbol{a}_{3}$ | rents                            | E | Gross Fixed Capital Formation |
| $\boldsymbol{a}_{4}$ | interest                         |   |                                |
| **A**              | Net product: $A=\sum a_{i}$      |   |                                |
| **B**              | Depreciation                     |   |                                |
|                    | **Gross Product**                    |   | **Gross Expenditure**             |

The production account shows the identity between income and expenditure, while the appropriation account shows how households allocate the income received from the lending of their factors of production to firms.

The capital account, in turn, shows the identity $\text{investment} \equiv \text{savings},$ which is nothing more than an alternative way of representing the identity $\text{product} \equiv \text{income} \equiv \text{expenditure}.$

### Opening the economy

So far we have worked with the simplest case, which is the one I should focus my research on, but it is interesting to relax the assumptions a bit. For that, we need to introduce a few additional concepts.

• Trade balance: the trade of goods with the rest of the world.

• Services and income balance: trade in services and factors of production (incomes such as profits and interest).

We now make a distinction between domestic product and national product. There is no single convention, but according to the SNA 93 we use the attribute “domestic” for “product” (domestic product), and “national” for “income” (national income). The idea is that we are usually interested, on the one hand, in GDP (gross domestic product), that is, the total product produced within the territory of the country, regardless of the origin of the factors of production responsible for it. On the other hand, we consider GNI (gross national income), which is the value added generated by factors of production owned by residents, regardless of the territory where this value is generated.

To obtain the national product of an economy, one must subtract from its domestic product the net income sent abroad or, if applicable, add to its domestic product the net income received from abroad. In most cases, developed countries are net exporters of capital and therefore receive net income from abroad, while the opposite occurs in less developed countries. We now proceed to the third version of the product account:

|                          | **Debit**                               |       | **Credit**                          |
|--------------------------|-----------------------------------------|-------|-------------------------------------|
| **I**                    | Imports of goods and services           | **G** | Exports of goods and services       |
| **J-H**                  | Net income sent [+] abroad              | **C** | Personal consumption                |
| **$\boldsymbol{a}_{1}$**   | wages                                   | **D** | Change in inventories               |
| **$\boldsymbol{a}_{2}$**   | profits                                 | **E** | Gross fixed capital formation       |
| **$\boldsymbol{a}_{3}$**   | rents                                  |       |                                     |
| **$\boldsymbol{a}_{4}$**   | interest                               |       |                                     |
| **A**                    | Net product ($A=\sum a_{i}$)            |       |                                     |
| **B**                    | Depreciation                           |       |                                     |
|                          | **Supply of Goods and Services**        |       | **Demand for Goods and Services**   |

Where net income is the aggregate of wages, profits, rents, and interest. It is important to remember that depreciation is not a transaction of any kind, but rather the devaluation—or, more precisely, a loss of value—of the capital stock, recorded in accounting terms.

The debit side brings together the sources of the supply of goods and services available in the economy, while the credit side records the uses of that supply, that is, where goods and services are allocated: consumption, inventory investment, fixed capital formation, and exports. Thus, debit corresponds to the origin or supply of resources, while credit corresponds to their destination.

### Introducing the government

The government collects direct taxes (which are levied on income or wealth, such as property tax and vehicle tax) and indirect taxes (which are levied on prices, such as VAT and excise taxes). Transfers are direct taxes with a negative sign; subsidies are indirect taxes with a negative sign. The two most important categories of transfers are, on the one hand, pensions and retirement benefits and, on the other hand, interest on public debt.

Tax is the generic designation for any type of revenue that the government is able to collect by virtue of being the government. Taxes (direct and indirect) are the most well-known form of public revenue, but in addition to them there are also fees (such as waste collection fees), betterment contributions (arising from public works), and other types of contributions (such as social security contributions and economic intervention levies, among others).

As for subsidies, in most cases they do not represent a redistribution of revenue collected through taxes, but rather the government’s waiver of revenue to which it would otherwise be entitled. For example, the government may wish to reduce the price of milk for final consumers and therefore waive the collection of the value-added tax (VAT) that would normally be levied on milk sales.

To deal with changes in prices due to taxes and subsidies, two concepts of product were introduced: the product at market prices, which includes the value of indirect taxes net of subsidies, and the product at factor cost, which does not include this additional value.

Now, the economy’s aggregate supply in a given period is the sum of gross domestic product at market prices and imports of non-factor goods and services. Aggregate demand, on the other hand, is the sum of GDP at market prices and exports of non-factor goods and services. The production framework is then:


|         | **Debit**                               |       | **Credit**                          |
|---------|-----------------------------------------|-------|-------------------------------------|
| **I**   | Imports of goods and services           | **G** | Exports of goods and services       |
| **J-H** | Net income sent [+] abroad              | **C** | Personal consumption                |
| **A**   | Net income ($\sum a_i$)                 | **L** | Government consumption              |
| **B**   | Depreciation                            | **D** | Change in inventories               |
| **Q-N** | Net indirect taxes                      | **E** | Gross fixed capital formation       |
|         | **Supply of Goods and Services**        |       | **Demand for Goods and Services**   |


Net indirect taxes are indirect taxes ($Q$) minus subsidies ($N$). We note that the government now appears as an additional source of demand. However, we do not directly find transfers, direct taxes, the government's current account balance, or other net current revenues, since here we are looking only at the product account and therefore consider only those items that directly affect output. These other elements appear, for example, in the appropriation account:

|         | **Debit**                        |                    | **Credit**      |
|---------|----------------------------------|--------------------|-----------------|
| **C**   | Personal consumption             | $\boldsymbol{a}_{1}$ | wages           |
| **P-M** | Net direct taxes                 | $\boldsymbol{a}_{2}$ | profits         |
| **R**   | Other net current receipts       | $\boldsymbol{a}_{3}$ | rents           |
| **F**   | Net private saving               | $\boldsymbol{a}_{4}$ | interest        |
|         | **Allocation of Net Income**     | **A**              | **Net Income**  |

Net direct taxes are direct taxes ($P$) minus transfers ($M$). To understand net private saving, we now turn to the capital account:

|       | **Debit**                              |       | **Credit**                |
|-------|----------------------------------------|-------|---------------------------|
| **D** | Change in inventories                  | **F** | Net private saving        |
| **E** | Gross fixed capital formation          | **B** | Depreciation              |
| **K** | Balance of payments current account balance | **O** | Government current account balance |
|       | **Total Gross Investment**             |       | **Total Gross Saving**    |

If we were to return to a closed economy without government, the credit side would contain only $F$ and $B$. Thus, net private saving is the portion of production that was not consumed, net of depreciation; that is,
$$
F = D + E - B,
$$
where $B$ is depreciation, $D$ is the change in inventories, and $E$ is gross fixed capital formation.

Other accounts that I will not discuss in detail at this stage include the external sector account:

|       | **Debit**                              |   | **Credit**                    |
|-------|----------------------------------------|---|-------------------------------|
| **G** | Exports of goods and services          | **I** | Imports of goods and services |
| **H** | Income received from abroad            | **J** | Income sent abroad            |
| **K** | Balance of payments current account balance |   |                               |
|       | **Total Debit**                        |   | **Total Credit**              |

And the government account:

|       | **Debit**                          |       | **Credit**                      |
|-------|------------------------------------|-------|---------------------------------|
| **L** | Government consumption             | **P** | Direct taxes                    |
| **M** | Transfers                          | **Q** | Indirect taxes                  |
| **N** | Subsidies                          | **R** | Other net current receipts      |
| **O** | Government current account balance |       |                                 |
|       | **Use of Revenue**                 |       | **Total Revenue**               |

Direct taxes are levied on both firms ($P.1$) and households ($P.2$). Item $R$ must also be included because income recipients make, in addition to direct tax payments, other types of payments directly to the government (such as fees, social security contributions, fines, or rents for the use of government-owned property), which constitute the government's other current revenues.

We must also consider $O$, because once the government is introduced into the system, it also becomes a source of saving. Thus, it represents the third source of saving, alongside the private sector and the external sector.

The internal consistency of the accounts is assumed to hold. One way to verify this is to sum the debit side of all five accounts and subtract from it the sum of the credit side of all five accounts. If the system is indeed balanced, the result of this operation must be zero.

$$
[(I+J-H+A+B+Q-N)+(C+P-M+R+F)+(D+E)+(G+H+K+L+M+N+O)]
$$

$$
-
$$

$$
[(G+C+L+D+E)+(A)+(F+B+K+O)+(I+J)+(P+Q+R)]
$$

$$
=0
$$

It is important to emphasize that this is only one model of the System of National Accounts (SNA 93), and it is not the version currently in use. However, because it is considerably simpler, I found it more suitable for exploration. Moreover, I placed particular emphasis on the product account.

In [ ]:
import numpy as np

In [ ]:
A = np.array([[45/500, 240/2900,15/1952],
              [90/500, 600/2900,210/1952],
              [0.00, 144/2900, 0.00]])
print('A matriz de coeficientes A é:')
print(A)
I = np.eye(3)
M=I-A
L = np.linalg.inv(M)
print('A matriz de Leontieff é:')
print(L)

A matriz de coeficientes A é:
[[0.09       0.08275862 0.00768443]
 [0.18       0.20689655 0.10758197]
 [0.         0.04965517 0.        ]]
A matriz L é:
[[1.12233089 0.11845059 0.02136762]
 [0.25644763 1.29648526 0.14144909]
 [0.01273395 0.0643772  1.00702368]]


In [ ]:
v = np.array([[200],[2000],[1808]])
print('Se a demanda é:')
print(v)
x=np.dot(L, v)
print('Então a produção bruta necessária é:')
print(x)

Se a demanda é:
[[ 200]
 [2000]
 [1808]]
Então a produção bruta necessária é:
[[ 500.]
 [2900.]
 [1952.]]


In [ ]:
print('A produção Bruta total é:',sum(x)[0])
print('A demanda total é:',sum(v)[0])
X = np.array([[A[0][0]*x[0][0],A[0][1]*x[1][0],A[0][2]*x[2][0]],
              [A[1][0]*x[0][0],A[1][1]*x[1][0],A[1][2]*x[2][0]],
              [A[2][0]*x[0][0],A[2][1]*x[1][0],A[2][2]*x[2][0]]])
print('E a matriz de insumos-produtos é:')
print(X)
print('E o valor adicionado é:')
v = np.array([[x[0][0]-np.sum(X[:, 0])],[x[1][0]-np.sum(X[:, 1])],[x[2][0]-np.sum(X[:, 2])]])
print(v)

A produção Bruta total é: 5352.0
A demanda total é: 4007.9999999999995
E a matriz de insumos-produtos é:
[[ 45. 240.  15.]
 [ 90. 600. 210.]
 [  0. 144.   0.]]
E o valor adicionado é:
[[ 365.]
 [1916.]
 [1727.]]


In [ ]:
# Para somar os valores de uma coluna, use np.sum() com axis=0
# Por exemplo, para somar a primeira coluna da matriz X:
sum_column_0 = np.sum(X[:, 0])
print(f"Soma da primeira coluna de X: {sum_column_0}")

# Para somar todas as colunas de X e obter um array com a soma de cada coluna:
sums_of_all_columns = np.sum(X, axis=0)
print(f"Soma de todas as colunas de X: {sums_of_all_columns}")